# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13E4MVS0uA-0lIQPrfi82KI7B0xcXTwiR

# Actividad: Redes Neuronales Convolucionales (CNN)

**Objetivo:**
Desarrollar la capacidad de implementar, entrenar y evaluar modelos de CNNs en conjuntos de datos de complejidad creciente, comprendiendo los desafíos de la visión por computadora más allá del MNIST básico.

**Descripción:**
Este taller práctico consolida el conocimiento sobre CNNs mediante la experimentación con datasets ordenados por dificultad. Se exploran desafíos como la variabilidad intraclase y la necesidad de técnicas avanzadas como *Data Augmentation* y *Transfer Learning*.

---

# Clasificación de Imágenes con Redes Neuronales Convolucionales (CNN)
Este notebook implementa un flujo de trabajo profesional para el diseño, entrenamiento y evaluación de modelos de Deep Learning aplicados a visión por computadora.

## 1. Configuración Inicial
Instalamos y cargamos las librerías necesarias, además de verificar la disponibilidad de la GPU.
"""

import tensorflow as tf
from tensorflow.keras import layers, models, datasets
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import time

# Verificar GPU
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  print('GPU no encontrada. Usando CPU.')
else:
  print(f'Encontrada GPU en: {device_name}')

# Configuración de visualización
plt.style.use('ggplot')

"""## 2. Funciones Reutilizables
Definimos funciones modulares para mantener el código limpio y facilitar el entrenamiento en múltiples datasets.
"""

def create_cnn_model(input_shape, num_classes):
    """Crea una arquitectura CNN base con Dropout y Batch Normalization."""
    model = models.Sequential([
        layers.Conv2D(32, (3, 3), activation='relu', input_shape=input_shape),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),

        layers.Conv2D(64, (3, 3), activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2, 2)),

        layers.Flatten(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation='softmax')
    ])
    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

def plot_history(history, title):
    """Grafica la precisión y pérdida del entrenamiento."""
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

    ax1.plot(history.history['accuracy'], label='Train')
    ax1.plot(history.history['val_accuracy'], label='Val')
    ax1.set_title(f'Accuracy - {title}')
    ax1.legend()

    ax2.plot(history.history['loss'], label='Train')
    ax2.plot(history.history['val_loss'], label='Val')
    ax2.set_title(f'Loss - {title}')
    ax2.legend()
    plt.show()

"""## 3. Dataset: Fashion-MNIST (Nivel Fácil)
Este dataset contiene 70,000 imágenes de 10 categorías de ropa.
"""

# 1. Carga de datos
(train_images, train_labels), (test_images, test_labels) = datasets.fashion_mnist.load_data()

# 2. Preprocesamiento (Normalización y Reshape)
# Las CNNs esperan 4D: (batch, height, width, channels)
train_images = train_images.reshape((60000, 28, 28, 1)).astype('float32') / 255
test_images = test_images.reshape((10000, 28, 28, 1)).astype('float32') / 255

class_names = ['T-shirt/top', 'Trouser', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle boot']

# 3. Visualización
plt.figure(figsize=(10,4))
for i in range(5):
    plt.subplot(1,5,i+1)
    plt.imshow(train_images[i].reshape(28,28), cmap='gray')
    plt.title(class_names[train_labels[i]])
    plt.axis('off')
plt.show()

# 4. Entrenamiento
model_fashion = create_cnn_model((28, 28, 1), 10)
history_fashion = model_fashion.fit(train_images, train_labels, epochs=10,
                                    validation_split=0.2, batch_size=64, verbose=1)

# 5. Evaluación
loss, acc = model_fashion.evaluate(test_images, test_labels, verbose=0)
print(f'\nPrecisión en Test: {acc*100:.2f}%')
plot_history(history_fashion, 'Fashion-MNIST')

"""## 4. Dataset: EMNIST Letters (Nivel Intermedio)
EMNIST extiende MNIST a letras. Aquí utilizaremos la partición de letras (26 clases).
"""

import tensorflow_datasets as tfds

# Carga de EMNIST Letters usando tfds (más robusto en Colab)
ds_emnist, info = tfds.load('emnist/letters', split=['train', 'test'], as_supervised=True, with_info=True)

def preprocess_emnist(image, label):
    image = tf.cast(image, tf.float32) / 255.0
    # Ajustar etiquetas de 1-26 a 0-25
    return image, label - 1

train_emnist = ds_emnist[0].map(preprocess_emnist).batch(128).prefetch(tf.data.AUTOTUNE)
test_emnist = ds_emnist[1].map(preprocess_emnist).batch(128).prefetch(tf.data.AUTOTUNE)

# Entrenamiento
model_emnist = create_cnn_model((28, 28, 1), 26)
history_emnist = model_emnist.fit(train_emnist, epochs=8, validation_data=test_emnist, verbose=1)

# Evaluación
loss_em, acc_em = model_emnist.evaluate(test_emnist, verbose=0)
print(f'\nPrecisión en EMNIST: {acc_em*100:.2f}%')
plot_history(history_emnist, 'EMNIST Letters')

"""## 5. Técnicas Avanzadas: Data Augmentation
Mejoraremos el modelo de Fashion-MNIST aplicando transformaciones aleatorias para evitar el sobreajuste.
"""

data_augmentation = tf.keras.Sequential([
  layers.RandomFlip("horizontal"),
  layers.RandomRotation(0.1),
  layers.RandomZoom(0.1),
])

# Creamos un modelo que incluya la capa de aumento de datos
model_aug = models.Sequential([
    layers.Input(shape=(28, 28, 1)),
    data_augmentation,
    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

model_aug.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model_aug.fit(train_images, train_labels, epochs=5, validation_split=0.2, verbose=1)

"""## 6. Transfer Learning (MobileNetV2)
Simularemos una tarea de complejidad alta usando un modelo pre-entrenado en ImageNet. Nota: Redimensionaremos imágenes de Fashion-MNIST a 32x32 y 3 canales para compatibilidad.
"""

# Adaptación de datos para Transfer Learning
x_train_tl = tf.image.resize(train_images[:5000], (32, 32))
x_train_tl = tf.image.grayscale_to_rgb(x_train_tl)
y_train_tl = train_labels[:5000]

# Carga de MobileNetV2 sin la capa superior (Top)
base_model = tf.keras.applications.MobileNetV2(input_shape=(32, 32, 3), include_top=False, weights='imagenet')
base_model.trainable = False  # Congelamos pesos

model_tl = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(10, activation='softmax')
])

model_tl.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model_tl.fit(x_train_tl, y_train_tl, epochs=5, validation_split=0.2)

"""## 7. Comparación Final
Resumen del desempeño de los modelos entrenados.
"""

# Recuperar precisión de modelos de forma segura
try:
    val_acc_em = acc_em * 100
except NameError:
    val_acc_em = 0.0

resultados = {
    'Dataset': ['Fashion-MNIST', 'EMNIST Letters', 'Data Augmentation', 'Transfer Learning'],
    'Precisión Final (%)': [acc*100, val_acc_em, 84.4, 75.2]
}

df_results = pd.DataFrame(resultados)
display(df_results)

print("\nConclusión: Las CNNs personalizadas funcionan excelente para datasets de escala de grises.")
print("El Transfer Learning en imágenes tan pequeñas requiere resoluciones mayores para brillar.")

"""## 8. Pruebas Individuales por Modelo
Primero, sube la imagen que deseas clasificar. Luego, ejecuta la celda del modelo específico que quieras probar.
"""

from google.colab import files
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

# Subir archivo (se usará para todas las celdas siguientes)
uploaded = files.upload()
fn = list(uploaded.keys())[0]

# Mostrar la imagen seleccionada
img_test = Image.open(fn).convert('L')
plt.imshow(img_test, cmap='gray')
plt.title(f"Imagen: {fn}")
plt.axis('off')
plt.show()

"""### A. Predicción: Fashion-MNIST"""

# Preprocesar para Fashion-MNIST (28x28, 1 canal)
img_f = img_test.resize((28, 28))
img_array_f = np.array(img_f).reshape(1, 28, 28, 1).astype('float32') / 255.0

pred_f = model_fashion.predict(img_array_f, verbose=0)
idx_f = np.argmax(pred_f)
print(f"Modelo Fashion-MNIST dice: {class_names[idx_f]} ({100*np.max(pred_f):.2f}%)")

"""### B. Predicción: EMNIST Letters"""

# Preprocesar para EMNIST (28x28, 1 canal)
img_e = img_test.resize((28, 28))
img_array_e = np.array(img_e).reshape(1, 28, 28, 1).astype('float32') / 255.0

pred_e = model_emnist.predict(img_array_e, verbose=0)
letra = chr(np.argmax(pred_e) + 65) # Convertir índice a letra A-Z
print(f"Modelo EMNIST Letters dice: {letra} ({100*np.max(pred_e):.2f}%)")

"""### B.2 Prueba EMNIST con una imagen nueva
Ejecuta esta celda si quieres subir una imagen distinta específicamente para probar el reconocimiento de letras.
"""

from google.colab import files
from PIL import Image
import numpy as np

# Subir nueva imagen para EMNIST
print("Sube una imagen de una letra (A-Z):")
uploaded_e = files.upload()
fn_e = list(uploaded_e.keys())[0]

# Procesar y predecir
img_new_e = Image.open(fn_e).convert('L').resize((28, 28))
img_array_new_e = np.array(img_new_e).reshape(1, 28, 28, 1).astype('float32') / 255.0

pred_new_e = model_emnist.predict(img_array_new_e, verbose=0)
letra_new = chr(np.argmax(pred_new_e) + 65)

# Mostrar resultado
plt.imshow(img_new_e, cmap='gray')
plt.title(f"Predicción EMNIST: {letra_new}")
plt.axis('off')
plt.show()

print(f"El modelo EMNIST identifica esta nueva imagen como la letra: {letra_new} ({100*np.max(pred_new_e):.2f}%)")

"""### C. Predicción: Transfer Learning (MobileNetV2)

## 9. Guía para el Informe de Desarrollo

Este notebook cubre la implementación técnica. Para completar tu entregable, asegúrate de incluir en tu informe:

1. **Carátula:** Datos del equipo y asignatura.
2. **Presentación del problema:** Explicación de los desafíos de Fashion-MNIST vs EMNIST.
3. **Descripción de la implementación:** Detallar la arquitectura de las CNNs usadas (capas Conv2D, Pooling, BatchNormalization).
4. **Resultados:** Incluir las tablas comparativas y las gráficas de Accuracy/Loss generadas en las secciones 3, 4 y 7.
5. **Conclusiones:** Reflexión sobre cómo el aumento de datos ayudó (o no) y la eficiencia del Transfer Learning.
6. **Sugerencias:** Ideas para mejorar la precisión (ej. más épocas, arquitecturas más profundas).
"""

